SUBCATEGORIES = [
    "Groceries",
    "Lunches/snacks at work",
    "Restaurants/take-out",
    "Clothing",
    "Laundry/dry cleaning",
    "Religious/charitable donations",
    "Movies/concerts/sporting events",
    "Video rentals/online movie services",
    "Pet care",
    "Hobbies/habits",
    "Haircuts/Beauty",
    "Birthdays/gifts",
    "Vacations",
    "Other living expenses",
]
